services:
  db:
    image: postgres:14-alpine
    container_name: chordenet
    ports:
      - "5440:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chordenet

volumes:
  postgres_data:
